Hash to curve as defined in the standard
dalek-cryptography/curve25519-dalek pull request #377
Opened 2021-11-11 13:55 UTC by iquerejeta

The current implementation is not compatible with the current definition of the standard. This PR provides a hash-to-curve implementation as defined in draft-irtf-cfrg-hash-to-curve-12.

* Implementation of `hash_to_field` as defined in the standard
* Implementation of `hash_to_curve` as defined in the standard, by changing the mechanism over which we chose the sign.
* For the point above, had to change the `elligator_encode` to return whether `eps` is a square or not (required for `hash_to_curve`).
* Included test vectors of the draft.
* Included `FieldElement::from_bytes_wide(bytes: &u8; 64])` to reduce integers encoded in 64 bytes.

2022-12-07 08:23 UTC, iquerejeta commented
I see in #438 that the function `hash_to_bytes` was deprecated. Is there any chance to include the `hash_to_curve` as defined in the [standard](https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/)? 
cc: @rozbb

2022-12-07 09:22 UTC, rozbb commented
Yes, thank u for following up. I do want to merge this but I haven't gotten a chance to do a proper review. We really need to get to a 4.0 release, so I think this might have to wait until 4.1. Thank you so much for this contribution. I promise it will get the attention it deserves.

2022-12-08 00:23 UTC, tarcieri commented
It would also be interesting if someone could attempt to impl the [`hash2curve` traits from the `elliptic-curve` crate](https://docs.rs/elliptic-curve/latest/elliptic_curve/hash2curve/index.html) i.e. as an optional dependency

2022-12-08 07:37 UTC, iquerejeta commented
Happy to do it 👍  given that there is no rush, I should be able to dedicate a few cycles in a reasonable amount of time.

2025-04-24 13:58 UTC, tarcieri commented
Well for starters, it's full of merge conflicts

2025-04-28 06:42 UTC, paweljakubas commented
Thank you very much @iquerejeta (I have also started rebasing your PR on Fri but you was quicker :smile: )
@tarcieri are we fine now? Thanks in advance for your help and time spent here and cheers :wave:

2025-04-30 06:50 UTC, paweljakubas commented
@tarcieri @rozbb @oleganza  can we do with @iquerejeta something more ?
Thanks in advance for your time and please do not be angry with me for my pinging :pray: 

We are working on VRF library based on dalek-cryptography and basing atm on this branch and we would like to have just master as dependency rather than branch. 

Cheers!

2025-05-08 15:35 UTC, abailly commented
Apologies for pestering you @tarcieri but we ([Amaru team](https://github.com/pragma-org/amaru)) ultimately depend on this PR to be included in a proper version of curve255159-dalek in order to simplify our dependencies on [VRF](https://github.com/txpipe/vrf) library and also to be able to request a proper audit on a stable code base. 
Is there anything we can help on to move this forward and cut a release in the near future?

2025-05-08 18:23 UTC, tarcieri commented
@abailly you should probably ask @rozbb. I'm working on a lot of prerequisites to the next releases and don't have time to review this, sorry

2025-05-09 05:27 UTC, abailly commented
Thanks a lot @tarcieri, waiting for @rozbb's feedback then 🙏

2025-05-09 13:27 UTC, tarcieri commented
I'll also note this looks fine to me at first glance, but I'd prefer one of us go through it in detail

2025-05-16 02:39 UTC, rozbb requested changes
Hi hi! Thank you so much for this. This overlapped with #612, which seems like a superset of this, and I was hoping it'd go faster. But it's not and that's fine!

I left a few comments here and there, but overall looks great!

2025-05-16 02:39 UTC, rozbb commented on curve25519-dalek/src/backend/serial/u64/constants.rs
> +pub(crate) const ED25519_SQRTAM2: FieldElement51 = FieldElement51::from_limbs([
Nit: can you add the following test to the end of `src/constants.rs`?

```rust
/// Test that ED25519_SQRTAM2 squared is MONTGOMERY_A_NEG - 2
#[test]
fn test_sqrt_a_minus_2() {
    let one = FieldElement::ONE;
    let a_minus_two = &(&constants::MONTGOMERY_A_NEG - &one) - &one;

    assert_eq!(constants::ED25519_SQRTAM2.square(), a_minus_two)
}
```

2025-05-16 02:39 UTC, rozbb commented on curve25519-dalek/src/edwards.rs
> +    pub fn hash_to_curve_dst<D>(bytes: &[u8], dst: &[u8]) -> EdwardsPoint
Can we rename `dst` to `domain_sep` or something similar, and update the docstring? `dst` reads too much like "destination" imo

2025-05-16 02:39 UTC, rozbb commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +    pub fn from_bytes_wide(hash: &[u8; 64]) -> FieldElement51 {
Question: this seems to only be implemented for the serial backends. Do the vector backends not need something like this?

2025-05-16 02:39 UTC, rozbb commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +        fe_f.0[0] = fe_f.0[0] + (hash[31] >> 7) as u64 * 19 + (hash[63] >> 7) as u64 * 722;
Where does this math come from?

2025-05-22 13:44 UTC, iquerejeta reviewed
Trying to refresh my memory with the first question!

2025-05-22 13:44 UTC, iquerejeta commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +    pub fn from_bytes_wide(hash: &[u8; 64]) -> FieldElement51 {
I added them only in serial backends to follow how the library is structured. These functions `from_bytes_wide` only exist for serial in the library.

2025-05-22 13:46 UTC, iquerejeta commented on curve25519-dalek/src/edwards.rs
> +    pub fn hash_to_curve_dst<D>(bytes: &[u8], dst: &[u8]) -> EdwardsPoint
We could also simply cal it `hash_to_curve`, given that that's how the spec is defined.

2025-05-23 09:28 UTC, iquerejeta commented on curve25519-dalek/src/edwards.rs
> +        let mont_v =
There are a few ways this is done. In libsodium, for example, they compute `v` via a square root, pick the sign accordingly, and then convert to Edwards using that sign ([see here](https://github.com/jedisct1/libsodium/blob/d537f3010a4e8e4ab5afdbf782799c48d8f09272/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c#L2739)).

What we do is different: note that `is_square` tells us the sign of the Montgomery `v` coordinate, not the Edwards `X`. However, the `to_edwards` function only lets us specify the sign of `X`, so we:

- Call `to_edwards` with an arbitrary sign (in our case, 0),
- Recompute `v` from the `u` and the Edwards `X` using the mapping formula (recall that `X = ED25519_SQRTAM2 * u / v`)
- Then flip the sign of `X` if the resulting sign of `v` doesn't match `is_sq ^ v.is_negative()`.

This avoids using square roots and works with our existing conversion interface (the current interface would _not_ allow us to do it the square root way, because there is no `Montgomery -> Edwards` conversion that takes both `(u, v)` as input). We could add code that enables it—happy to benchmark it.

2025-05-23 10:48 UTC, abailly commented
@rozbb Would it be possible to get approval to run workflows so that we can check CI is passing?

2025-05-26 08:16 UTC, daxpedda commented on curve25519-dalek/src/field.rs
> +        }
Checking for overflow on slice length with a `usize` is unnecessary, you would run out of memory before it overflows.

2025-05-26 08:26 UTC, daxpedda commented on curve25519-dalek/src/field.rs
> +        let z_pad = [0u8; 128];
Now that we do handle `BlockSizeUser` correctly, we also need to enforce [further requirements from the spec](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-13.html#section-5.4.1-4):
> For correctness, H requires b <= s.

This can be done via:
```rust
BlockSizeUser<BlockSize: Greater<D::OutputSize, Output = True>>
```

2025-05-26 10:30 UTC, daxpedda approved these changes

2025-05-26 10:40 UTC, daxpedda commented
Just a quick summary on what could be addressed in future improvements:
- Return a `Result` instead of panicking with invalid DSTs.
- Support hashes not with an output size of 64 bytes.
- Support [DSTs larger than 255 bytes](https://www.rfc-editor.org/rfc/rfc9380.html#name-using-dsts-longer-than-255-).
- Support `expand_message_xof`. ([`expand_message_xmd` is the suggested suite](https://www.rfc-editor.org/rfc/rfc9380.html#name-suites-for-curve25519-and-e) so it is the right default)

2025-05-27 06:04 UTC, rozbb commented on curve25519-dalek/src/edwards.rs
> +        let mont_v =
Sorry, my brain is a bit fried but I'll try to understand better. To be clear, my absolute top concern is maintainability. It would be way easier for me if all the formulas in this PR used notation directly from the spec. Do you think that'd be possible? I don't mind some added code (eg the conversion method you mentioned) to get there. I'll even accept a performance hit if necessary. I think @tarcieri would agree

2025-05-27 06:12 UTC, rozbb commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +        fe_f.0[0] = fe_f.0[0] + (hash[31] >> 7) as u64 * 19 + (hash[63] >> 7) as u64 * 722;
I added some comments that explain it all, but I have one last question: why does the `38 * ` expression below guaranteed to not overflow? Is there a property in libsodium that guarantees this? Do we have the same?

2025-05-27 10:37 UTC, iquerejeta commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +        fe_f.0[0] = fe_f.0[0] + (hash[31] >> 7) as u64 * 19 + (hash[63] >> 7) as u64 * 722;
`FieldElement51` represents an element of the field `2^255 - 19`. In other words, it represents a number of size 255 bits. With 4 limbs of `u64`, we would have enough for representing these numbers. However, `FieldElement51` represents the number with 5 limbs of 51 bits, and as [documented](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek/src/backend/serial/u64/field.rs#L30): 
```
the coefficients are allowed to grow up to 2^54 between reductions modulo p
```

So even if the type is u64, we can do these operations here with the guarantee that we won't have an overflow.

2025-05-27 10:49 UTC, iquerejeta commented on curve25519-dalek/src/edwards.rs
> +        let mont_v =
I'd be happy to do that. I'm wondering if it makes sense to change the `elligator_encode` function directly, and perform elligator as specified in the standard. What I have in mind is that we implement the straight line implementation they present in the standard ([here](https://www.rfc-editor.org/rfc/rfc9380.html#appendix-F.3). And then we have two functions, an elligator2 for montgomery, and an elligator2 for edwards. WDYT?

2025-05-28 04:18 UTC, rozbb commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +        fe_f.0[0] = fe_f.0[0] + (hash[31] >> 7) as u64 * 19 + (hash[63] >> 7) as u64 * 722;
If `from_bytes` produces an element with a limb x = 2^51, then isn’t it the case that x * 38 > x * 32 = 2^56 > 2^54?

2025-05-28 10:08 UTC, iquerejeta commented on curve25519-dalek/src/edwards.rs
> +        let mont_v =
I started trying to do this, and there's some functionality missing. The only `pow` implementation is `pow2k`. Following the inline implementation we need to compute 
```
y11 = tv2^c4
```
where
```
c4 = (q - 5) / 8
```

with c4 not being a power of 2 (see step 16 [here](https://datatracker.ietf.org/doc/html/rfc9380#name-curve25519-q-5-mod-8-k-1)). Don't know if I'm missing a trick here. I think at this point it would be easier to properly document, rather than implementing new functions. If you are happy with that path I can add proper documentation to the function, and leave it as is.

2025-05-29 10:03 UTC, iquerejeta commented on curve25519-dalek/src/edwards.rs
> +        let mont_v =
I've added a comment. I decided to link [this](https://datatracker.ietf.org/doc/html/rfc9380#name-elligator-2-method) section, instead of the inline section, as I believe its easier to follow along. Let me know what you think.

2025-05-30 07:23 UTC, rozbb commented on curve25519-dalek/src/backend/serial/u64/field.rs
> +        fe_f.0[0] = fe_f.0[0] + (hash[31] >> 7) as u64 * 19 + (hash[63] >> 7) as u64 * 722;
Ah it looks like you indeed can pass limbs up to 2^64

https://github.com/dalek-cryptography/curve25519-dalek/blob/dd5bd108d6985491acb3de25497fb082a29c9fb7/curve25519-dalek/src/backend/serial/u64/field.rs#L293

So the current impl should work. Could you add a comment saying this when you get a chance?

2025-06-11 08:14 UTC, paweljakubas commented
hi @iquerejeta @rozbb @tarcieri  great work on both implementation and review side! Are we fine now to merge this PR ?

2025-06-11 14:04 UTC, rozbb commented
I believe we’re still waiting on a refactor to write the Elligator functions in the way the spec writes them, right?

2025-06-11 16:07 UTC, iquerejeta commented
I think I misunderstood then. I thought we agreed to simply document the function properly, as following the steps as they are presented in the draft required additional functionality. The discussion was [here](https://github.com/dalek-cryptography/curve25519-dalek/pull/377#discussion_r2111469297)

2025-06-19 05:46 UTC, abailly commented
Is there anything we (@paweljakubas , @iquerejeta or I) can do to help merging this PR?

2025-06-19 18:15 UTC, tarcieri commented
@abailly can you resolve the merge conflicts?

@rozbb I would suggest merging after that, and leaving updating the Elligator implementation as a followup (there are also several open PRs to do that, although I'm not sure if any actually follow the spec)

2025-06-19 19:39 UTC, abailly commented
Thanks, that would be awesome!

2025-06-24 09:33 UTC, iquerejeta commented
Rebase done 👍 
ccL @rozbb

2025-06-24 14:56 UTC, tarcieri commented
@iquerejeta there are some deprecations you'll need to fix

2025-06-25 06:27 UTC, iquerejeta commented
My bad 🙏  forgot about those in the rebase.

2025-06-26 05:22 UTC, rozbb commented
Thank you, and sorry for the delay. Will make time for this tomorrow

2025-06-27 07:22 UTC, rozbb commented on curve25519-dalek/src/field.rs
> +    fn from_hash_wide() {
One last question I promise: Where are these test vectors from?

2025-06-27 07:22 UTC, rozbb commented
Ok, just cleaned up docs and clarified the origin of some KATs. I left just 1 question, namely where the from_bytes_wide test vectors came from. Other than that, I think we're good to go!

2025-06-27 07:54 UTC, iquerejeta commented on curve25519-dalek/src/field.rs
> +    fn from_hash_wide() {
I must admit that I do not remember. It's been a while. I was looking for those test vectors in the libsodium implementation or some drafts (which were the most likely sources) but couldn't find any. 

I'm happy to regenerate them from any source you'd like and document it accordingly.

2025-06-28 18:36 UTC, rozbb commented
This is confusing to me. It seems the `fiat` backend doesn't have a `FieldElement::from_bytes_wide` function, which is necessary for `hash_to_field`. For some reason, this compiled in the past. Why?

2025-06-30 11:36 UTC, iquerejeta commented
What should we do about the fiat backend? The logic of the from_bytes_wide is not from fiat crypto 🤔

2025-06-30 14:19 UTC, rozbb commented
@iquerejeta Well my question is: what was it doing when the build was succeeding? Shouldn’t the fiat build have always been failing?

2025-06-30 15:22 UTC, iquerejeta commented
Yeah, that's a good question. I have no idea why. I believe we never had an implementation of from_bytes_wide for fiat.

2025-07-04 19:24 UTC, tarcieri commented
Regarding `fiat-crypto` and wide reductions, this might be helpful: https://words.filippo.io/wide-reduction/

2025-07-05 06:13 UTC, rozbb commented
Thank you @tarcieri, that gave me the idea to make `from_bytes_wide` generic over any field element, rather than over specific implementations. This simplifies the implementation, makes it work for `fiat`, and also does not detectibly slow down `hash_to_curve` on my machine.

Do you wanna do one last look-over? I had to bump the `fiat-crypto` dependency because we needed `fiat_25519_from_bytes` to be a const fn, which it previously wasn't. I assume that's fine, since we don't export anything from there.

2025-07-05 13:54 UTC, tarcieri approved these changes
LGTM

2025-07-05 20:01 UTC, merged

2025-07-05 20:01 UTC, rozbb commented
Thank you so much @iquerejeta @tarcieri and @daxpedda !!

2025-07-05 20:48 UTC, abailly commented
🎉 Thank you everyone! Looking forward to next release so that we can release our stuff too :)

2025-07-07 08:00 UTC, iquerejeta commented
🎉  Thanks everyone! 🙏